task_manager/urls.py
from django.contrib import admin
from django.contrib.auth.views import LogoutView
from django.urls import path
from tasks.views import *
from tasks.apiviews import *
from rest_framework_nested.routers import SimpleRouter, NestedSimpleRouter

router = SimpleRouter()
router.register(r"api/v1/task", TaskViewSet)
nested_router = NestedSimpleRouter(router, r"api/v1/task", lookup="task")
nested_router.register("history", HistoryViewSet, basename="task-history")

urlpatterns = (
    [
        path("", RedirectRootToTasks.as_view()),
        path("admin/", admin.site.urls),
        path("taskapi", TaskListAPI.as_view()),
        path("tasks/", GenericTaskView.as_view()),
        path("user/signup/", UserCreateView.as_view()),
        path("user/login/", UserLoginView.as_view()),
        path("user/logout/", LogoutView.as_view()),
        path("create-task/", GenericTaskCreateView.as_view()),
        path("update-task/<pk>/", GenericTaskUpdateView.as_view()),
        path("detail-task/<pk>/", GenericTaskDetailView.as_view()),
        path("delete-task/<pk>/", GenericTaskDeleteView.as_view()),
        path("completed_tasks/", GenericCompletedTaskView.as_view()),
        path("complete_task/<pk>/", GenericCompleteTaskView.as_view()),
        path("all_tasks/", GenericAllTasksView.as_view()),
        path("settings/<pk>/", EmailSettingsView.as_view()),
        # path("sample/", send_email_view),
    ]
    + router.urls
    + nested_router.urls
)

tasks/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import pre_save
from django.dispatch import receiver
from django.utils import timezone
from datetime import datetime


STATUS_CHOICES = (
    ("PENDING", "PENDING"),
    ("IN_PROGRESS", "IN_PROGRESS"),
    ("COMPLETED", "COMPLETED"),
    ("CANCELLED", "CANCELLED"),
)


class Task(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField()
    completed = models.BooleanField(default=False)
    created_date = models.DateTimeField(auto_now=True)
    deleted = models.BooleanField(default=False)
    priority = models.IntegerField()
    status = models.CharField(
        max_length=100, choices=STATUS_CHOICES, default=STATUS_CHOICES[0][0]
    )
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)

    class Meta:
        constraints = [
            models.CheckConstraint(check=models.Q(priority__gt=0), name="priority_gt_0")
        ]

    def __str__(self):
        return self.title


class EmailSettings(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    email_time = models.TimeField(editable=True, default=timezone.now)
    email_date = models.DateField(default=timezone.now)
    email_enable = models.BooleanField(default=True)


class History(models.Model):
    prev_status = models.CharField(
        max_length=50, choices=STATUS_CHOICES, default=STATUS_CHOICES[0][0]
    )
    updated_status = models.CharField(
        max_length=50, choices=STATUS_CHOICES, default=STATUS_CHOICES[0][0]
    )
    changed_date = models.DateField(auto_now=True)
    task_changed = models.ForeignKey(
        Task, on_delete=models.CASCADE, null=True, blank=True
    )


@receiver(pre_save, sender=Task)
def generate_history(sender, instance, **kwargs):
    if Task.objects.filter(pk=instance.id).exists():
        prev_task = Task.objects.get(pk=instance.id)
        if instance.status == prev_task.status:
            return
        History(
            prev_status=prev_task.status,
            updated_status=instance.status,
            task_changed=instance,
        ).save()

tasks/forms.py
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.core.exceptions import ValidationError
from django.forms import ModelForm, EmailField, DateTimeField
from django.contrib.auth.models import User
from tasks.models import Task, EmailSettings
from datetime import datetime, timedelta

input_field_style = "bg-slate-100 w-full my-1 rounded-lg border-slate-100  shadow-inner px-4 py-3 focus:border-red-500 active:border-red-500 focus:ring-red-500 checked:bg-red-500"
check_box_style = "h-6 w-6 rounded border-slate-100  shadow-inner border-none bg-slate-100 checked:bg-red-500 text-red-500 focus:ring-red-500"


class TaskCreateForm(ModelForm):
    def __init__(self, *args, **kwargs):
        super(TaskCreateForm, self).__init__(*args, **kwargs)
        for visible in self.visible_fields():
            try:
                if visible.field.widget.input_type == "checkbox":
                    visible.field.widget.attrs["class"] = check_box_style
                else:
                    visible.field.widget.attrs["class"] = input_field_style
            except:
                visible.field.widget.attrs["class"] = input_field_style
                visible.field.widget.attrs["rows"] = 5

    def clean_title(self):
        title = self.cleaned_data["title"]
        if len(title) < 5:
            raise ValidationError("Title too small, must be greater than 5 characters!")
        return title.capitalize()

    def clean_priority(self):
        priority = self.cleaned_data["priority"]
        if priority <= 0:
            raise ValidationError("Prioriry must be greater than zero!")
        return priority

    class Meta:
        model = Task
        fields = ["title", "description", "priority", "completed", "status"]


class CustomUserCreateForm(UserCreationForm):
    class Meta:
        model = User
        fields = ("username", "email")

    def __init__(self, *args, **kwargs):
        super(CustomUserCreateForm, self).__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs["class"] = input_field_style
        self.fields["email"].required = True


class CustomUserLoginForm(AuthenticationForm):
    def __init__(self, *args, **kwargs):
        super(CustomUserLoginForm, self).__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs["class"] = input_field_style


class EmailSettingsForm(ModelForm):
    def __init__(self, *args, **kwargs):
        super(EmailSettingsForm, self).__init__(*args, **kwargs)
        for visible in self.visible_fields():
            if visible.field.widget.input_type == "checkbox":
                visible.field.widget.attrs["class"] = check_box_style
            else:
                visible.field.widget.attrs["class"] = input_field_style

    class Meta:
        model = EmailSettings
        fields = ("email_time", "email_enable")

tasks/views.py
# Add your Views Here
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView
from django.core.exceptions import ValidationError
from django.db import transaction
from django.forms import ModelForm
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.views import View
from django.views.generic.base import RedirectView, TemplateView
from django.views.generic.detail import DetailView, SingleObjectMixin
from django.views.generic.edit import CreateView, DeleteView, DeletionMixin, UpdateView
from django.views.generic.list import ListView
from django.core.mail import send_mail
from django.conf import settings

from tasks.forms import *
from tasks.models import Task, EmailSettings


class TaskCompletedCount:
    def get_context_data(self, *args, **kwargs):
        base_qs = Task.objects.filter(user=self.request.user)
        active_tasks = base_qs.filter(deleted=False)
        completed_tasks = active_tasks.filter(completed=True)
        context = super().get_context_data(*args, **kwargs)
        context["completed_count"] = completed_tasks.count()
        context["total_count"] = active_tasks.count()
        return context


class RedirectRootToTasks(RedirectView):
    url = "/tasks"


class AuthorisedTaskManager(LoginRequiredMixin):
    def get_queryset(self):
        return Task.objects.filter(deleted=False, user=self.request.user).order_by(
            "priority"
        )


class UserLoginView(LoginView):
    form_class = CustomUserLoginForm
    template_name = "user_login.html"


class UserCreateView(CreateView):
    form_class = CustomUserCreateForm
    template_name = "user_create.html"
    success_url = "/user/login"

    def form_valid(self, form):
        self.object = form.save()
        self.object.save()
        EmailSettings(user=self.object).save()
        return HttpResponseRedirect(self.get_success_url())


class EmailSettingsView(UpdateView):
    model = EmailSettings
    form_class = EmailSettingsForm
    template_name = "email_settings.html"
    success_url = "/tasks"


class GenericCompleteTaskView(AuthorisedTaskManager, View, SingleObjectMixin):
    success_url = "/tasks"

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        Task.objects.filter(id=self.object.id, user=self.request.user).update(
            completed=True
        )
        return HttpResponseRedirect(self.success_url)


class GenericAllTasksView(TaskCompletedCount, AuthorisedTaskManager, ListView):
    template_name = "all_tasks.html"
    context_object_name = "tasks"
    paginate_by = 4


class GenericTaskDeleteView(AuthorisedTaskManager, DeleteView):
    model = Task
    template_name = "task_delete.html"
    success_url = "/tasks"


class GenericTaskDetailView(AuthorisedTaskManager, DetailView):
    model = Task
    template_name = "task_detail.html"


@transaction.atomic
def task_priority_check(priority, user):
    """
    A function to check if any two tasks have the same priority
    if so, then cascade update the priorities such that no two tasks have the same priority
    """

    task_lst = (
        Task.objects.select_for_update()
        .filter(
            deleted=False,
            user=user,
            completed=False,
            priority__gte=priority,
        )
        .order_by("priority")
    )

    update_lst = []

    for task in task_lst:
        if task.priority != priority:
            break
        task.priority += 1
        priority += 1
        update_lst.append(task)

    Task.objects.bulk_update(update_lst, ["priority"])


class TaskFormValidMixin:
    def form_valid(self, form):
        priority = form.cleaned_data["priority"]
        if form.cleaned_data["completed"] == False:
            if form.has_changed() and "priority" in form.changed_data:
                task_priority_check(priority, self.request.user)
        self.object = form.save()
        self.object.user = self.request.user
        self.object.save()
        return HttpResponseRedirect(self.get_success_url())


class GenericTaskCreateView(TaskFormValidMixin, LoginRequiredMixin, CreateView):
    form_class = TaskCreateForm
    template_name = "task_create.html"
    success_url = "/tasks"


class GenericTaskUpdateView(TaskFormValidMixin, AuthorisedTaskManager, UpdateView):
    model = Task
    form_class = TaskCreateForm
    template_name = "task_update.html"
    success_url = "/tasks"


class GenericCompletedTaskView(TaskCompletedCount, LoginRequiredMixin, ListView):
    template_name = "completed.html"
    context_object_name = "tasks"
    paginate_by = 4

    def get_queryset(self):
        return Task.objects.filter(completed=True, user=self.request.user).order_by(
            "priority"
        )


class GenericTaskView(TaskCompletedCount, LoginRequiredMixin, ListView):
    template_name = "tasks.html"
    context_object_name = "tasks"
    paginate_by = 4

    def get_queryset(self):
        base_qs = Task.objects.filter(user=self.request.user)
        active_tasks = base_qs.filter(deleted=False, completed=False).order_by(
            "priority"
        )
        return active_tasks

templates/all_tasks.html
{% extends "tasks_base.html" %} {%block task_title%} All {%endblock%}
{#-------------#} {% block task_list %}

<section
	class="grid grid-cols-3 w-full gap-10 text-red-500 text-xl font-semibold my-2"
>
	<div>
		<a href="/all_tasks">
			<div class="bg-red-100 rounded-full py-2 px-7 text-center w-fit">All</div>
		</a>
	</div>
	<div>
		<a href="/tasks">
			<div class="text-black py-2 px-7 hover:text-red-500 smooth-effect">
				Pending
			</div>
		</a>
	</div>
	<div>
		<a href="/completed_tasks">
			<div class="text-black py-2 px-7 hover:text-red-500 smooth-effect">
				Completed
			</div>
		</a>
	</div>
</section>

{% if tasks %}
<section style="min-height: 50vh">
	{% for task in tasks %}

	<div
		class="flow-root bg-slate-100 drop-shadow-sm my-6 py-5 px-6 rounded-xl hover:scale-105 smooth-effect"
	>
		<a href="/detail-task/{{task.id}}/">
			<div class="float-left w-3/5">
				{% if task.completed %}
				<div class="text-xl font-medium text-rose-600">
					<del>{{task.title}}</del>
					<span
						class="bg-red-400 text-zinc-50 font-bold text-sm rounded-full ml-1.5"
						style="padding: 0.3rem 0.6rem"
					>
						{{task.priority}}
					</span>
				</div>
				<div class="text-slate-400">
					{{task.created_date|date:"D j M"}}
					<span
						class="text-xs font-semibold {%if task.status == 'PENDING'%}text-blue-500{%elif task.status == 'COMPLETED'%}text-amber-500{%elif task.status == 'IN_PROGRESS'%}text-green-500{%else%}text-rose-500{%endif%} ml-0.5"
						>{{ task.status }}</span
					>
				</div>

				{% else %}
				<div class="text-xl font-medium text-gray-900">
					{{task.title}}
					<span
						class="bg-red-400 text-zinc-50 font-bold text-sm rounded-full ml-1"
						style="padding: 0.3rem 0.6rem"
					>
						{{task.priority}}
					</span>
				</div>
				<div class="text-slate-500">
					{{task.created_date|date:"D j M"}}
					<span
						class="text-xs font-semibold {%if task.status == 'PENDING'%}text-blue-500{%elif task.status == 'COMPLETED'%}text-amber-500{%elif task.status == 'IN_PROGRESS'%}text-green-500{%else%}text-rose-500{%endif%} ml-0.5"
						>{{ task.status }}</span
					>
				</div>
				{% endif %}
			</div>
		</a>

		<div
			class="float-right grid grid-cols-2 gap-3 items-center justify-items-center mt-0.5"
		>
			<a href="/update-task/{{task.id}}/">
				<div class="bg-teal-400 rounded-xl p-3 hover:bg-teal-500 smooth-effect">
					<svg
						xmlns="http://www.w3.org/2000/svg"
						width="24"
						height="24"
						viewBox="0 0 24 24"
						fill="none"
						stroke="white"
						stroke-width="2"
						stroke-linecap="round"
						stroke-linejoin="round"
						class="feather feather-edit-2"
					>
						<path
							d="M17 3a2.828 2.828 0 1 1 4 4L7.5 20.5 2 22l1.5-5.5L17 3z"
						></path>
					</svg>
				</div>
			</a>

			<a href="/delete-task/{{task.id}}/">
				<div class="bg-rose-500 rounded-xl p-3 hover:bg-rose-600 smooth-effect">
					<svg
						xmlns="http://www.w3.org/2000/svg"
						width="24"
						height="24"
						viewBox="0 0 24 24"
						fill="none"
						stroke="white"
						stroke-width="2"
						stroke-linecap="round"
						stroke-linejoin="round"
						class="feather feather-trash"
					>
						<polyline points="3 6 5 6 21 6"></polyline>
						<path
							d="M19 6v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6m3 0V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2"
						></path>
					</svg>
				</div>
			</a>
		</div>
	</div>

	{% endfor %}
</section>

{%else%}
<section
	style="
		min-height: 50vh;
		display: flex;
		justify-content: center;
		align-items: center;
	"
	class="bg-slate-100 rounded-xl my-5"
>
	<span class="text-lg font-medium text-slate-600 text-center">
		No tasks to display!
		<br />
		<span class="text-gray-400 font-normal">
			Add a few tasks, you'll see all of your tasks here!
		</span>
	</span>
</section>
{%endif%} {%endblock%}

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
	<head>
		<meta charset="UTF-8" />
		<meta http-equiv="X-UA-Compatible" content="IE=edge" />
		<meta name="viewport" content="width=device-width, initial-scale=1.0" />
		<script src="https://cdn.tailwindcss.com?plugins=forms"></script>

		<style type="text/tailwindcss">
			@layer utilities {
				.content-auto {
					content-visibility: auto;
				}
			}

			.smooth-effect {
				@apply transition duration-300 ease-in-out;
			}

			.btn-red-lg {
				@apply bg-red-500 rounded-xl drop-shadow-md px-10 py-4 text-lg text-white w-full hover:bg-red-600 focus:scale-95 active:drop-shadow-none smooth-effect;
			}

			::-moz-selection {
				/* Code for Firefox */
				color: white;
				background: #f75d5d;
			}

			::selection {
				color: white;
				background: #f75d5d;
			}
		</style>
		<title>{% block title %}{% endblock %}</title>
	</head>
	<body>
		<div class="grid justify-items-center items-center h-screen">
			{% block content %}{% endblock %}
		</div>
	</body>
</html>

templates/completed.html
{% extends "tasks_base.html" %} {%block task_title%} Completed {%endblock%}
{#-------------#} {% block task_list %}

<section
	class="grid grid-cols-3 w-full gap-10 text-red-500 text-xl font-semibold my-2"
>
	<div>
		<a href="/all_tasks">
			<div class="text-black py-2 px-7 hover:text-red-500 smooth-effect">
				All
			</div></a
		>
	</div>
	<div>
		<a href="/tasks">
			<div class="text-black py-2 px-7 hover:text-red-500 smooth-effect">
				Pending
			</div>
		</a>
	</div>
	<div>
		<a href="/completed_tasks">
			<div class="bg-red-100 rounded-full py-2 px-7 text-center w-fit">
				Completed
			</div>
		</a>
	</div>
</section>

{% if tasks %}
<section style="min-height: 50vh">
	{% for task in tasks %}

	<div
		class="flow-root bg-slate-100 drop-shadow-sm my-6 py-5 px-6 rounded-xl hover:scale-105 smooth-effect"
	>
		<a href="/detail-task/{{task.id}}/">
			<div class="float-left w-3/5">
				<div class="text-xl font-medium text-gray-900">
					{{task.title}}
					<span
						class="bg-red-400 text-zinc-50 font-bold text-sm rounded-full ml-1"
						style="padding: 0.3rem 0.6rem"
						>{{task.priority}}</span
					>
				</div>
				<div class="text-slate-500">{{task.created_date|date:"D j M"}}
					<span
						class="text-xs font-semibold {%if task.status == 'PENDING'%}text-blue-500{%elif task.status == 'COMPLETED'%}text-amber-500{%elif task.status == 'IN_PROGRESS'%}text-green-500{%else%}text-rose-500{%endif%} ml-0.5"
						>{{ task.status }}</span
					>
				</div>
			</div>
		</a>

		<div
			class="float-right grid grid-cols-2 gap-3 items-center justify-items-center mt-0.5"
		>
			<a href="/update-task/{{task.id}}/">
				<div class="bg-teal-400 rounded-xl p-3 hover:bg-teal-500 smooth-effect">
					<svg
						xmlns="http://www.w3.org/2000/svg"
						width="24"
						height="24"
						viewBox="0 0 24 24"
						fill="none"
						stroke="white"
						stroke-width="2"
						stroke-linecap="round"
						stroke-linejoin="round"
						class="feather feather-edit-2"
					>
						<path
							d="M17 3a2.828 2.828 0 1 1 4 4L7.5 20.5 2 22l1.5-5.5L17 3z"
						></path>
					</svg>
				</div>
			</a>

			<a href="/delete-task/{{task.id}}/">
				<div class="bg-rose-500 rounded-xl p-3 hover:bg-rose-600 smooth-effect">
					<svg
						xmlns="http://www.w3.org/2000/svg"
						width="24"
						height="24"
						viewBox="0 0 24 24"
						fill="none"
						stroke="white"
						stroke-width="2"
						stroke-linecap="round"
						stroke-linejoin="round"
						class="feather feather-trash"
					>
						<polyline points="3 6 5 6 21 6"></polyline>
						<path
							d="M19 6v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6m3 0V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2"
						></path>
					</svg>
				</div>
			</a>
		</div>
	</div>

	{% endfor %}
</section>

{%else%}
<section
	style="
		min-height: 50vh;
		display: flex;
		justify-content: center;
		align-items: center;
	"
	class="bg-slate-100 rounded-xl my-5"
>
	<span class="text-lg font-medium text-slate-600 text-center">
		No Completed Tasks!
		<br />
		<span class="text-gray-400 font-normal">
			Complete a few tasks and come back here!
		</span>
	</span>
</section>
{%endif%} {%endblock%}

templates/tasks.html
{% extends "tasks_base.html" %} {%block task_title%} Pending {%endblock%}
{#-------------#} {% block task_list %}

<section
	class="grid grid-cols-3 w-full gap-10 text-red-500 text-xl font-semibold my-2"
>
	<div>
		<a href="/all_tasks">
			<div class="text-black py-2 px-7 hover:text-red-500 smooth-effect">
				All
			</div></a
		>
	</div>
	<div>
		<a href="/tasks">
			<div class="bg-red-100 rounded-full py-2 px-7 text-center w-fit">
				Pending
			</div>
		</a>
	</div>
	<div>
		<a href="/completed_tasks">
			<div class="text-black py-2 px-7 hover:text-red-500 smooth-effect">
				Completed
			</div>
		</a>
	</div>
</section>

{% if tasks %}
<section style="min-height: 50vh">
	{% for task in tasks %}

	<div
		class="flow-root bg-slate-100 drop-shadow-sm my-6 py-5 px-6 rounded-xl hover:scale-105 smooth-effect"
	>
		<a href="/detail-task/{{task.id}}/">
			<div class="float-left w-3/5">
				<div class="text-xl font-medium text-gray-900">
					{{task.title}}
					<span
						class="bg-red-400 text-zinc-50 font-bold text-sm rounded-full ml-1"
						style="padding: 0.3rem 0.6rem"
						>{{task.priority}}</span
					>
				</div>
				<div class="text-slate-500">
					{{task.created_date|date:"D j M"}}
					<span
						class="text-xs font-semibold {%if task.status == 'PENDING'%}text-blue-500{%elif task.status == 'COMPLETED'%}text-amber-500{%elif task.status == 'IN_PROGRESS'%}text-green-500{%else%}text-rose-500{%endif%} ml-0.5"
						>{{ task.status }}</span
					>
				</div>
			</div>
		</a>

		<div
			class="float-right grid grid-cols-3 gap-3 items-center justify-items-center mt-0.5"
		>
			<!-- <a href="/complete_task/{{task.id}}/"> -->
			<form action="/complete_task/{{task.id}}/" method="POST">
				{% csrf_token %}

				<button
					type="submit"
					class="bg-emerald-400 rounded-xl p-3 hover:bg-emerald-500 smooth-effect"
				>
					<svg
						xmlns="http://www.w3.org/2000/svg"
						width="24"
						height="24"
						viewBox="0 0 24 24"
						fill="none"
						stroke="white"
						stroke-width="2.5"
						stroke-linecap="round"
						stroke-linejoin="round"
						class="feather feather-check"
					>
						<polyline points="20 6 9 17 4 12"></polyline>
					</svg>
				</button>
			</form>

			<!-- </a> -->
			<a href="/update-task/{{task.id}}/">
				<div class="bg-teal-400 rounded-xl p-3 hover:bg-teal-500 smooth-effect">
					<svg
						xmlns="http://www.w3.org/2000/svg"
						width="24"
						height="24"
						viewBox="0 0 24 24"
						fill="none"
						stroke="white"
						stroke-width="2"
						stroke-linecap="round"
						stroke-linejoin="round"
						class="feather feather-edit-2"
					>
						<path
							d="M17 3a2.828 2.828 0 1 1 4 4L7.5 20.5 2 22l1.5-5.5L17 3z"
						></path>
					</svg>
				</div>
			</a>
			<a href="/delete-task/{{task.id}}/">
				<div class="bg-rose-500 rounded-xl p-3 hover:bg-rose-600 smooth-effect">
					<svg
						xmlns="http://www.w3.org/2000/svg"
						width="24"
						height="24"
						viewBox="0 0 24 24"
						fill="none"
						stroke="white"
						stroke-width="2"
						stroke-linecap="round"
						stroke-linejoin="round"
						class="feather feather-trash"
					>
						<polyline points="3 6 5 6 21 6"></polyline>
						<path
							d="M19 6v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6m3 0V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2"
						></path>
					</svg>
				</div>
			</a>
		</div>
	</div>

	{% endfor %}
</section>

{%else%}
<section
	style="
		min-height: 50vh;
		display: flex;
		justify-content: center;
		align-items: center;
	"
	class="bg-slate-100 rounded-xl my-5"
>
	<span class="text-lg font-medium text-slate-600 text-center">
		No Pending Tasks!
		<br />
		<span class="text-gray-400 font-normal">
			Grab a cup of coffee ☕ to celebrate!
		</span>
	</span>
</section>
{%endif%} {%endblock%}

templates/tasks_base.html
{% extends "base.html" %} {% block title %}{% block task_title %}
{#-------------#} {% endblock %}Tasks{% endblock %} {% block content%}

<div id="content-holder" class="">
	<div class="flow-root py-4">
		<div class="float-left text-5xl font-bold grid grid-cols-2">
			<div>Hi, {{request.user}}!</div>
			<div class="h-9 w-9 mt-3 ml-3 hover:rotate-45 smooth-effect">
				<a href="/settings/{{request.user.id}}" class="">
					<svg
						xmlns="http://www.w3.org/2000/svg"
						viewBox="0 0 20 20"
						fill="#363636"
					>
						<path
							fill-rule="evenodd"
							d="M11.49 3.17c-.38-1.56-2.6-1.56-2.98 0a1.532 1.532 0 01-2.286.948c-1.372-.836-2.942.734-2.106 2.106.54.886.061 2.042-.947 2.287-1.561.379-1.561 2.6 0 2.978a1.532 1.532 0 01.947 2.287c-.836 1.372.734 2.942 2.106 2.106a1.532 1.532 0 012.287.947c.379 1.561 2.6 1.561 2.978 0a1.533 1.533 0 012.287-.947c1.372.836 2.942-.734 2.106-2.106a1.533 1.533 0 01.947-2.287c1.561-.379 1.561-2.6 0-2.978a1.532 1.532 0 01-.947-2.287c.836-1.372-.734-2.942-2.106-2.106a1.532 1.532 0 01-2.287-.947zM10 13a3 3 0 100-6 3 3 0 000 6z"
							clip-rule="evenodd"
						/>
					</svg>
				</a>
			</div>
		</div>
		<a href="/user/logout">
			<div
				class="float-right text-xl font-semibold text-red-600 pt-3 hover:text-red-400 transition"
			>
				Logout
			</div>
		</a>
	</div>

	<section class="text-slate-500 w-full py-2 text-lg">
		{{completed_count}} of {{total_count}} tasks completed
	</section>

	{% block task_list %} {% endblock %}

	<section
		class="grid grid-cols-6 text-gray-700 text-center mb-6 gap-2 font-medium"
	>
		<a
			href="?page={%if page_obj.has_previous %} {{page_obj.previous_page_number}} {% endif %}"
			><div class="bg-slate-200 p-3 rounded-xl hover:bg-gray-300 smooth-effect">
				Prev
			</div></a
		>

		<div class="col-span-4 bg-slate-200 p-3 rounded-xl">
			Page {{page_obj.number}} of {{paginator.num_pages}}
		</div>
		<a
			href="?page={%if page_obj.has_next %} {{page_obj.next_page_number}} {% endif %}"
			><div class="bg-slate-200 p-3 rounded-xl hover:bg-gray-300 smooth-effect">
				Next
			</div></a
		>
	</section>

	<section class="mb-10">
		<a href="/create-task">
			<div class="btn-red-lg text-center">Add</div>
		</a>
	</section>
</div>
{% endblock %}